name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Zig
        run: |
          ./.devcontainer/install_zig.sh
      - name: Build
        run: zig build
